---
- name: running system_package tasks
  ansible.builtin.include_tasks: system_package.yml
  loop: "{{ system_package | dict2items }}"
  loop_control:
    label: "{{ system_package_item['key'] }}"
    loop_var: system_package_item
  when:
    system_package is defined
