---
galaxy_info:
  role_name: system_package
  author: turcumihaiioan
  description: role for ansible.builtin.package

  license: GPL-3.0-only

  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - package
    - system

dependencies: []
